### PR TITLE
A few improvements

### PR DESCRIPTION
**Pull request by MeLlamoPablo**
Hey there. First of all, I'll be using your framework for my project wich I'll upload to GitHub soon, so thank you. Now, I've made some changes that you may want to consider adding to your project:

1. **Muted the file_get_contents() function in userInfo.php. The file will now die() and output an error if it isn't able to access the Steam API for some reason.**    
Please, do consider making this change: with the current script, if the server doesn't reach the Steam servers (i.e: Steam is down), ```file_get_contents()``` will display a warning to the user with the URL used, and this URL contains the API key. We do not want the user to be able to access it; this is a security issue.
2. **userInfo.php will not do anything if the user hasn't logged in**.    
I know that in the example you handle this manually by including only userInfo.php when the user has logged in, but a good framework should take care of everything for you. In the current script, including this file without an user session wastes resources, increases load time and displays warnings. With this fix, it simply won't do anything.
3. **Added the constant STEAMAUTH_LOGOUT_LINK**.    
Its value is ```steamauth/logout.php``` and it is an alternative to ```logoutbutton()```, wich provides more flexibility. With ```logoutbutton()``` you get a simple, non-customizable button, but with the constant you can make your own button, or simply have a logout link.

Many thanks for your time.

### CODE REVIEW

**Comment by BlackCetha** [comment]
Good improvements, except that constant.
Why would one rather type `<a href="<?=STEAMAUTH_LOGOUT_LINK ?>">...` than just `<a href="steamauth/logout.php">`?

**Comment by MeLlamoPablo** [comment]
Hi,

* I used the constant because, since I won't be using the ```logoutbutton()``` function, I wanted to provide an alternative, and I thought it'd be clearer that way. I'm not sure if you can modify my changes before merging. If you want me to edit this, I can do that.
* I'm used to ```echo``` before ```die()``` because if you pass ```die()``` an integer, it won't output it. Thus, if you wanted to output an integer before dying, you'd have to do it by doing ```echo``` before. In this case it's useless indeed, but as I said, it's a habit of mine. Feel free to change it.

**Comment by BlackCetha** [comment]
I cannot change your Pull Request. Go ahead and edit the files in your fork. It will automatically add theese changes to the PR.

**Comment by MeLlamoPablo** [comment]
Ok, I've commited the new changes.

**Comment by BlackCetha** [comment]
This looks ready to merge from my side now.
Great job

**Comment by SmItH197** [comment]
Sorry about the delay, been really busy with exams. Thanks for your help! :)

**Pull request merged**
