### PR TITLE
URL-Generation fix, remove die()

### PR DESCRIPTION
**Pull request by BlackCetha**
The die() in userInfo.php made it possible for the complete page to stop
working without the option for displaying a error message. Librarys
should never die() in cases where it is out of the control of the
developer.

### CODE REVIEW

**Comment by BlackCetha** [comment]
This fixes #71 and #68

**Comment by mustique33** [comment]
Same for me.. It used to work and now 'just' broke... keeps '/?login' does nothing.

**Comment by andrewda** [comment]
@mustique33 I highly doubt this has anything to do with this PR, as it's already been implemented.

**Comment by BlackCetha** [comment]
As you might have noticed, this PR got merged July 17th.

**Pull request merged**
