### PR TITLE
Updating User Information | Include to Require

### PR DESCRIPTION
**Pull request by RedSparr0w**
## REAMDE.md
- Added information on how to update user info
- example on how to update user info if older than 24 hours

## userInfo.php
- Changed `$_SESSION['steam_uptodate']` to be timestamp `time()` rather than true (can be used to update user info if older than specified time)
- Removed 1 level of indentation
- changed include to require as it is required in order to function correctly
- moved require inside `if` as it is not needed otherwise

## steamauth.php
- changed includes to requires as they are required in order to function
correctly
- [removed brackets from require](http://php.net/manual/en/function.require.php#75875)
- inside if `headers_sent()` closed and reopened php tags rather than echoing the html
- added `exit;` to update and logout
- moved `require 'openid.php';` inside of `if (isset($_GET['login'])){` as this is the only time it is needed

## demo.php
- add `$steamprofile['steam_uptodate'] ` to demo.php page
- close `<td>` on same line

_Note: updating this list as changes happen_

### CODE REVIEW

**Comment by lithium720** [comment]
Why update only if longer than 24hrs? You've already made the request for information..

**Comment by RedSparr0w** [comment]
incase of a new username/profile picture can easily [change the amount of time](https://github.com/RedSparr0w/SteamAuthentication/blob/master/steamauth/steamauth.php#L67) on:

```php
if (isset($_GET['update']) || !empty($_SESSION['steam_uptodate']) && $_SESSION['steam_uptodate']+(24*60*60) /* 24hrs */ < time()){ 
```

**Comment by lithium720** [comment]
I'm aware of this, but doesn't this all update every time the sign in anyways?

**Comment by RedSparr0w** [comment]
yes, it does update each time they signin.

but if you remember the user for more than ex: 24hrs then the information wont be updated until you manually update it or they are forgotten/session expires and have to sign back in

**Comment by RedSparr0w** [comment]
probably does not need to by default be built into the update check.

could probably just put info in the readme about how to use the `$_SESSION['steam_uptodate']` time

but still think this:
```php
$_SESSION['steam_uptodate']=time();
```
will be more useful than:
```php
$_SESSION['steam_uptodate']=true;
```

as it provides aditional information which can be used easily

**Comment by lithium720** [comment]
Oh okay cool. Maybe this is something that could go into SteamConfig.php for convenience?

**Comment by RedSparr0w** [comment]
only problem with putting it in `SteamConfig.php` is that means you need to require this file every time just for a few numbers (the amount of time to add)

**Comment by lithium720** [comment]
And what makes that an issue?

**Comment by RedSparr0w** [comment]
just a bit better performance (although the file is really tiny)

**Comment by lithium720** [comment]
Like so tiny that It's probably worth putting in SteamConfig.php so it's convenient to change and people can know it's there when they inevitably don't read the readme.

**Comment by RedSparr0w** [comment]
good point.

have moved it to `SteamConfig.php` as `$steamauth['updateinterval']`

**Comment by BlackCetha** [comment]
Would you mind splitting your PR up?
It is always one PR, one feature ideally.

**Comment by BlackCetha** [comment]
Thinking about it, adding automatic updates make no sense.

By standart configuration PHP sessions last only as long as the browser is open, wich in most cases is way less than 24 hours. This means it has no benefit to 98% of the users.

We are also taking away control from the user once again. The purpose of this **library** is to provide a easy-to-use login function that pulls data from the Steam API on login.
As you may have noticed many sites that provide steam logins are not pulling data frequently. In order to update your profile, you have to manually start the process.
If we would just blindly update the data, it could break databases or applications that relates to said data.
It does also consume API-calls wich is never a good thing. By standart, you only get 10,000 a day.
This may seem way to much for anyone to use, but I can assure you that some sites that use this library hit this limit every day. Adding this "feature" would only make the situation worse.

Why don't we just let every user decide that for themselfes? The previously used solution worked fine for that and a auto-update, if needed, is really easy to do.

To draw a conclusion here, the auto-update functionality doesn't have any benefit for most users with standart configuration and can just handled by the users of this library themselfes.

**Comment by RedSparr0w** [comment]
This wouldn't automatically update all users information, as it's based off your session. So would only update your profile if your session has lasted longer than the specified time (1 day in example) and you visit the page again while your session is still active.

If your session ended and you had to sign in again it would automatically grab updated data again as it already does.

So most users would not be affected by this due to sessions by default being until browser closed and not everyone specifying longer times.

[Also the api call limit is 100,000 per day](https://steamcommunity.com/dev/apiterms)

I don't necessarily think the auto updating should be built in but I think 'steam_uptodate' should have some sort of value such as time() rather than just true as to have more usefulness

Sent from my iPhone

On 28/03/2016, at 10:36 pm, BlackCetha <notifications@github.com<mailto:notifications@github.com>> wrote:


Thinking about it, adding automatic updates make no sense.

By standart configuration PHP sessions last only as long as the browser is open, wich in most cases is way less than 24 hours. This means it has no benefit to 98% of the users.

We are also taking away control from the user once again. The purpose of this library is to provide a easy-to-use login function that pulls data from the Steam API on login.
As you may have noticed many sites that provide steam logins are not pulling data frequently. In order to update your profile, you have to manually start the process.
If we would just blindly update the data, it could break databases or applications that relates to said data.
It does also consume API-calls wich is never a good thing. By standart, you only get 10,000 a day.
This may seem way to much for anyone to use, but I can assure you that some sites that use this library hit this limit every day. Adding this "feature" would only make the situation worse.

Why don't we just let every user decide that for themselfes? The previously used solution worked fine for that and a auto-update, if needed, is really easy to do.

To draw a conclusion here, the auto-update functionality doesn't have any benefit for most users with standart configuration and can just handled by the users of this library themselfes.

-

**Comment by RedSparr0w** [comment]
have removed the auto update part, and moved it to the readme as information.

**Comment by SmItH197** [comment]
Hi, I've merged this. I made some very slight language/grammar/layout changes in the readme.

**Pull request merged**
