### PR TITLE
Another readme update

### PR DESCRIPTION
**Pull request by bman46**
Before u add it can u check to make sure the the code i got in the wiki is good, think it is but want more verification, thq.

### CODE REVIEW

**Comment by SmItH197** [comment]
`Create a custom page which is called after logging in`  - isn't this what `$steamauth['loginpage']` is for?

`Converting Unix Time Stamp` - why declare `$timestamp`? Why not just use `$steamprofile['lastlogoff']` as is?

**Comment by bman46** [comment]
I did not write the article for "Create a custom page" just the "Converting unix timestamp one. And i declared $timestamp for no reason, u can delete it and change it.

**Comment by SmItH197** [comment]
Ah my bad

**Comment by bman46** [comment]
we should probably delete that page though, it seems useless.

**Comment by RedSparr0w** [comment]
maybe also add a link to the wiki in the read me or to the specific page in the wiki your referring to so it will be easier for people to find aswell [=

**Comment by bman46** [comment]
@RedSparr0w good idea, ill add that.

**Comment by bman46** [comment]
done!

**Comment by SmItH197** [comment]
Merged, had to fix some conflicts, also changed the markdown for the Wiki links to format properly.

**Comment by bman46** [comment]
k thq

**Pull request merged**
