### PR TITLE
Modify steamauth.php for support of multiple vars in url?

### PR DESCRIPTION
**Pull request by CaptainJackas**
Heard many people were struggling with this so made a small modification that gives users the opportunity to let their visitors login from pages with variables in the url. I made this optional, so it also works without any vars. Users would only have to change the GET involved in the url and change the var name in the $returnpage.

### CODE REVIEW

**Comment by BlackCetha** [comment]
Nopenopenopenope

This broke the entire lib for two month until we rolled back a while ago

**Comment by CaptainJackas** [comment]
I know steam strips all GET params from the return url that's why I proposed this solution, because I do want to return to an url with params. And by just adding this little piece of code it works perfectly for me and should for others.

**Comment by BlackCetha** [comment]
After ten minutes of thinking about how this would work, I am still certain it cant.
You still need to pull ?urlparam through steam.

Your code executes when a user returns from steam, right?

**Comment by CaptainJackas** [comment]
Yeah, but when a user clicks on the login button the param can be send along with the ?login request like:
`<a href="?login&urlparam=1"> `
Because of that 'urlparam' can be reached in the steamauth.php file just like ?login already is.

**Comment by CaptainJackas** [comment]
Oow just realised that the loginbutton() function should be edited for this since I used a custom link in my code instead of loginbutton(). But then it would still work the same as it does now.

**Comment by RedSparr0w** [comment]
something like this would probably work better.

```php
$_SESSION['steamid'] = $matches[1];
$_GET['openid_return_to']=str_replace("login","",$_GET['openid_return_to']);
if (!headers_sent()) {
	header('Location: '.$_GET['openid_return_to']);
	exit;
} else {
	?>
	<script type="text/javascript">
		window.location.href="<?=$_GET['openid_return_to']?>";
	</script>
	<noscript>
		<meta http-equiv="refresh" content="0;url=<?=$_GET['openid_return_to']?>" />
	</noscript>
	<?php
	exit;
}
```

it may leave you with 
`index.php?&someParam=someVal or index.php` -OR- `someParam=someVal&&someOtherParam=SomeOtherVal`
depending where in the url the "login" param is
but it will still work correctly.

note:what im talking about is the `?&` or `&&` in the url,

**Comment by BlackCetha** [comment]
In my opinion, we should leave it to the developers how they deal with this.
It's not really complicated and there are many possibile ways of doing it.

**Comment by bman46** [comment]
@CaptainJackas did u test it?

**Comment by SmItH197** [comment]
Sorry for the delay, I've been away travelling for the last few months, I have to agree with others that adding extra features such as this could create more problems than use cases. I think it should be up to the individual developer to implement features such as this.

**Pull request closed without merging**
