### PR TITLE
add || empty to example

### PR DESCRIPTION
**Pull request by radek3911**
this should add a little security

### CODE REVIEW

**Comment by RedSparr0w** [comment]
We could also just use [`empty()`](http://php.net/manual/en/function.empty.php) instead.
>A variable is considered empty if it does not exist or if its value equals FALSE.
empty() does not generate a warning if the variable does not exist.

**Comment by radek3911** [comment]
Like without the !isset yea that would work too.

**Comment by radek3911** [comment]
Sorry for the commit spam, I don't know how to revert commit in the web version.

**Review by kaitokid222 — APPROVED** [review]

**Comment by radek3911** [comment]
Closing PR after no activity.

**Pull request closed without merging**
