### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by xxalfa**

### CODE REVIEW

**Comment by BlackCetha** [comment]
Please split your changes into different PRs with a distinct change each.

**Comment by xxalfa** [comment]
No longer possible - the code is not too long, everything I've changed is easily recognizable.

**Comment by BlackCetha** [comment]
You are changing every single line in every file you touched. This makes the diff completely unreadable.

**Comment by xxalfa** [comment]
If I change something, then completely. I have not changed much, just beautify something - of course, can also reject my proposal.

**Comment by xxalfa** [comment]
The structure was outdated, it is a logical consequence to change it.

With the README.md I have to agree with you, it must be recreated.

**Comment by BlackCetha** [comment]
Who besides you says the structure is outdated?
You're just blindly changing everything in the project while not even willing or able to describe what you've done.

**Comment by xxalfa** [comment]
Of course I'm the only one. What have I done? The nested folder structure removed, given unique file names. Foreign scripts that change appearance are removed. Readability performed according to my standards.

Simply general improvement, I have not reinvented.

**Comment by BlackCetha** [comment]
A few things wrong with that:
- Just changing a library to your standards is not accepted. Instead, you should push code in the library's style only.
- The nested folder structure is a feature of it's API. You will be breaking every single application that uses the library. Same with the file names.
- You're switching the downstream library. While this might be beneficial, your lack of coorporation on the matter of discussing your changes makes it hard to believe that you're aware of the possible side effects.

And then there's this nonsense:
`$steam_authentication[ 'avatar' ] = isset( $_SESSION[ 'avatar' ] ) ? $_SESSION[ 'avatar' ] : null;`
Definitely shows your level of experience with PHP or that your coding style is questionable at best. In PHP, variables that are not initialized behave like `null`.

**Comment by xxalfa** [comment]
It has a reason why I use it. Notice: Undefined index: avatar in steam-authentication.php on line 80

`$steam_authentication[ 'avatar' ] = $_SESSION[ 'avatar' ];`

Your arguments are of course correct, so a distribution is not necessary.

**Pull request closed without merging**
